from semantic_router import Route, SemanticRouter
from semantic_router.index import LocalIndex
from semantic_router.encoders import DenseEncoder
from embedding import Embedding
import os
import pickle

class PhoBERTEncoder(DenseEncoder):

    def __init__(self, embedding_model):
        super().__init__(name="phobert", dim=768)
        self._model = embedding_model

    def __call__(self, texts):
        return self._model.embed_documents(texts)

phobert_embedding = Embedding()
encoder = PhoBERTEncoder(phobert_embedding)
index_path = "cache/router/router_index.pkl"

chitchat = Route(
    name="chitchat",
    utterances=[
        "Xin chào",
        "Chào bạn",
        "Chào buổi sáng",
        "Chào buổi trưa",
        "Chào buổi tối",
        "Bạn khỏe không?",
        "Bạn có khỏe không?",
        "Bạn đang làm gì thế?",
        "Rất vui được gặp bạn",
        "Hân hạnh làm quen",
        "Chúc bạn một ngày tốt lành",
        "Chúc ngủ ngon",
        "Chúc mừng năm mới",
        "Chúc may mắn",
        "Mọi việc ổn chứ?",
        "Bạn ở đâu vậy?",
        "Bạn làm nghề gì?",
        "Bạn bao nhiêu tuổi?",
        "Bạn đang học hay đi làm?",
        "Bạn thích đọc sách không?",
        "Bạn có thích nghe nhạc không?",
        "Bạn có xem phim không?",
        "Bạn thích ăn món gì nhất?",
        "Bạn thích uống cà phê hay trà?",
        "Bạn có thú cưng không?",
        "Bạn thích đi du lịch chứ?",
        "Bạn đi làm bằng gì?",
        "Bạn có anh chị em không?",
        "Bạn có thích thể thao không?",
        "Bạn hay chơi game không?",
        "Bạn thích mùa nào nhất?",
        "Bạn thích biển hay núi?",
        "Bạn hay đi chơi với bạn bè không?",
        "Bạn thường dậy lúc mấy giờ?",
        "Bạn thích ngủ nướng không?",
        "Bạn có hay tập thể dục không?",
        "Bạn có nấu ăn không?",
        "Bạn thích ăn ngọt hay mặn?",
        "Bạn có thể kể một câu chuyện không?",
        "Bạn có thể kể một trò đùa không?",
        "Bạn có thích hoa không?",
        "Bạn có hay chụp hình không?",
        "Bạn có hay nghe podcast không?",
        "Bạn có thích học ngoại ngữ không?",
        "Bạn đang học tiếng Anh à?",
        "Bạn có thể giúp mình không?",
        "Rất vui khi nói chuyện với bạn",
        "Cảm ơn vì đã lắng nghe",
        "Cảm ơn nhiều nhé",
        "Tạm biệt",
        "Hẹn gặp lại",
        "Chúc buổi tối vui vẻ",
        "Chúc một ngày an lành",
        "Bạn có đi chơi cuối tuần không?",
        "Bạn làm gì dịp lễ?",
        "Bạn có thích Tết không?",
        "Bạn thích ăn bánh chưng hay bánh tét?",
        "Bạn có hay đi xem pháo hoa không?",
        "Ê",
        "Alo",
        "Hello nè",
        "Có gì mới không?",
        "Dạo này sao rồi?",
        "Dạo này ổn chứ?",
        "Rảnh không?",
        "Ngồi đâu vậy?",
        "Đi đâu đó?",
        "Ngon không trời?",
        "Nghe xong thấy ham",
        "Đỉnh thật sự",
        "Chuẩn không cần chỉnh",
        "Chuẩn bài",
        "Chuẩn vãi",
        "Cười xỉu :))",
        "Haha",
        "Hehe",
        "Kkk",
        "Lol",
        "Vãi thật",
        "Đúng rồi đó",
        "Trời ơi",
        "Ôi trời",
        "Thật không tin nổi",
        "Hên ghê",
        "Xui ghê",
        "Sao xui dữ vậy",
        "Ghê ta",
        "Ngon dữ",
        "Nghe đã ghê",
        "Mlem mlem",
        "Ngonnnn",
        "Quá đãaaa",
        "Được của nó",
        "Xịn xò",
        "Chất lượng phết",
        "Khét lẹt",
        "Nói nghe coi",
        "Kể đi chứ",
        "Có gì hot?",
        "Có biến gì mới không?",
        "Làm tí không?",
        "Uống cf không?",
        "Đi nhậu không?",
        "Tối nay rảnh hông?",
        "Đi coi phim không?",
        "Đi chơi hông?",
        "Đi chill không?",
        "Đi karaoke không?",
        "Đi phượt không?",
        "Đi dạo không?",
        "Chém gió xíu",
        "Tám chuyện không?",
        "Nghe drama chưa?",
        "Drama mới nè",
        "Hóng quá trời",
        "Kệ đi",
        "Thôi kệ",
        "Mặc kệ nó",
        "Chán ghê",
        "Nghe chán thật",
        "Buồn ngủ quá",
        "Đói bụng quá",
        "Thèm ăn gì quá",
        "Thèm trà sữa",
        "Thèm bún bò",
        "Thèm phở",
        "Thèm ăn vặt",
        "Đang đói xỉu",
        "Mệt quá",
        "Mệt muốn xỉu",
        "Mệt ghê luôn",
        "Buồn ghê",
        "Chán đời",
        "Bó tay",
        "Thua luôn",
        "Xạo quá",
        "Xạo thiệt hả?",
        "Tin được không?",
        "Thiệt hông?",
        "Có chắc hông?",
        "Đùa hả?",
        "Nói thiệt đi",
        "Nói giỡn hả?",
        "Nói xạo ghê",
        "Nghe cũng hay đó",
        "Nghe cũng hợp lý",
        "Ờ ha",
        "Ờ đúng rồi",
        "Ờ ờ",
        "Ờ thôi",
        "Ừ",
        "Ừ nè",
        "Ừ đúng rồi đó",
        "Ừ thì vậy đó",
        "Ừ thôi kệ",
        "Ừm",
        "Ừm chắc vậy",
        "Ừm nghe cũng được",
        "Ừm để coi",
        "Ừa",
        "Ừa cũng được",
        "Ờ được đó",
        "Ờ ngon đó",
        "Ờ để suy nghĩ",
        "Ờ để coi đã",
        "Ờ vậy đi",
        "Ờ ha chuẩn luôn",
        "Ờ ngon nghẻ",
        "Ờ xịn phết",
        "Ơ kìa",
        "Ơ thế à",
        "Ơ dễ thương ghê",
        "Ơ vãi",
        "Ơ ghê vậy",
        "Ơ sao thế",
        "Ơ trời",
        "Ơ chết rồi",
        "Ơ kkk",
        "Ơ nghe cũng lạ",
        "Ơ đúng luôn",
        ":))",
        "^^",
        ":v",
        "=))",
        "kkk",
        "lol",
        "hihi",
        "haha",
        "huhu",
        "zzz",
        "😅",
        "😂",
        "🤣",
        "😍",
        "🥰",
        "🤔",
        "🙄",
        "😎",
        "😭",
        "😢",
        "😴",
        "🤯",
        "😳",
        "😜",
        "😆",
        "🤪",
        "😏",
        "👌",
        "👍",
        "👎",
        "🙏",
        "🔥",
        "✨",
        "⭐",
        "💯",
        "❤️",
        "💔",
        "💕",
        "💖",
        "🥳",
        "🤗",
        "😇",
        "🤩",
        "😋",
        "🤤",
        "😱",
        "🤡",
        "💀",
        "☠️",
        "👻",
        "👀",
        "🫶",
        "🫠",
    ]
)

Academic_regulation = Route (
    name="Academic_Advising",
    utterances=[
    "Học phí một tín chỉ là bao nhiêu?",
    "Sinh viên nợ học phí có được thi không?",
    "Hạn cuối đóng học phí là ngày nào?",
    "Nếu trễ hạn đóng học phí thì sao?",
    "Có chính sách miễn giảm học phí không?",
    "Bao lâu thì hoàn tiền học phí khi xin thôi học?",
    "Sinh viên nghèo có được hỗ trợ học phí không?",
    "Có học bổng toàn phần không?",
    "Điều kiện để được học bổng khuyến khích học tập là gì?",
    "Học bổng cấp bao nhiêu tiền một tháng?",
    "Học phí ngành Công nghệ thông tin bao nhiêu?",
    "Khi nào trường thông báo mức học phí mới?",
    "Có chính sách miễn giảm cho sinh viên con thương binh không?",
    "Sinh viên có thể đóng học phí theo đợt không?",
    "Đóng học phí online bằng cách nào?",
    "Có được trả góp học phí không?",
    "Nếu đóng thừa học phí có được hoàn lại không?",
    "Có cần biên lai học phí khi làm thủ tục tốt nghiệp không?",
    "Sinh viên quốc tế có mức học phí khác không?",
    "Học phí có tăng theo từng năm không?",
    "Nếu không đủ tiền đóng học phí thì có bị thôi học không?",
    "Có ưu đãi học phí cho sinh viên đạt thành tích cao không?",
    "Khi nào có thông báo về hạn đóng học phí?",
    "Có cần đóng học phí trước khi đăng ký môn không?",
    "Nếu đóng sai học phí thì xử lý thế nào?",
    "Học phí ngành Y cao hơn ngành khác không?",
    "Có giảm học phí cho sinh viên mồ côi không?",
    "Nếu chưa đóng học phí thì có được cấp bảng điểm không?",
    "Học phí ngành Kinh tế bao nhiêu một kỳ?",
    "Học phí chương trình chất lượng cao là bao nhiêu?",
    "Có giảm học phí cho sinh viên vùng sâu vùng xa không?",
    "Học phí có bao gồm phí thi lại không?",
    "Sinh viên phải đóng phí giáo trình không?",
    "Có thể đóng học phí tại ngân hàng không?",
    "Nếu quên đóng học phí thì sao?",
    "Có học bổng giảm 100% học phí không?",
    "Sinh viên đóng học phí bằng thẻ tín dụng được không?",
    "Có hỗ trợ học phí cho sinh viên khuyết tật không?",
    "Có thể đóng học phí nhiều kỳ một lần không?",
    "Có thu thêm phí khi đóng học phí trễ hạn không?",
    "Sinh viên bị kỷ luật có được giảm học phí không?",
    "Có miễn học phí cho sinh viên sư phạm không?",
    "Sinh viên có được đóng học phí theo từng môn không?",
    "Nếu rút môn thì học phí được hoàn lại không?",
    "Có phụ phí khi học môn tiếng Anh không?",
    "Học phí ngành Du lịch bao nhiêu?",
    "Nếu không đóng học phí thì có được bảo lưu không?",
    "Học phí ngành Luật có cao không?",
    "Có được giảm học phí khi đạt giải nghiên cứu khoa học không?",
    "Khi nào sinh viên được hoàn phí ký túc xá?",
    "Một kỳ được đăng ký tối đa bao nhiêu tín chỉ?",
    "Muốn học vượt thì phải làm sao?",
    "Học tối thiểu bao nhiêu tín chỉ một kỳ?",
    "Có thể đăng ký môn học ngoài chương trình không?",
    "Bao nhiêu tín chỉ thì được xét tốt nghiệp?",
    "Có thể học song song hai ngành không?",
    "Thời gian bảo lưu tối đa bao nhiêu kỳ?",
    "Xin bảo lưu học tập cần điều kiện gì?",
    "Học vượt năm có được không?",
    "Có thể học nhiều lớp cùng một môn không?",
    "Bao lâu thì hoàn thành một tín chỉ?",
    "Một môn học bao nhiêu tín chỉ?",
    "Có giới hạn số tín chỉ trong toàn khóa học không?",
    "Nếu rớt môn thì tín chỉ có tính không?",
    "Có cần học đủ tín chỉ tự chọn không?",
    "Có thể đổi tín chỉ tự chọn sang bắt buộc không?",
    "Nếu học lại thì tín chỉ có bị tính thêm không?",
    "Có thể học chương trình song bằng không?",
    "Một tín chỉ gồm bao nhiêu tiết học?",
    "Có bắt buộc học giáo dục quốc phòng không?",
    "Có bao nhiêu tín chỉ thể chất?",
    "Có được công nhận tín chỉ từ trường khác không?",
    "Điều kiện để đăng ký học vượt tín chỉ là gì?",
    "Sinh viên năm nhất được học tối đa mấy tín chỉ?",
    "Có cần học đầy đủ tín chỉ kỹ năng mềm không?",
    "Tín chỉ tự chọn có được thay thế bằng tín chỉ khác không?",
    "Nếu chuyển ngành thì tín chỉ được bảo lưu không?",
    "Có được miễn một số tín chỉ không?",
    "Nếu học chậm tín chỉ có bị cảnh cáo không?",
    "Có thể học lớp tín chỉ khác khoa không?",
    "Sinh viên có thể hoãn học một tín chỉ không?",
    "Có phải đóng thêm phí khi học vượt tín chỉ không?",
    "Nếu bỏ môn thì tín chỉ có được trả lại không?",
    "Có cần học đầy đủ tín chỉ ngoại ngữ không?",
    "Có được công nhận tín chỉ từ chương trình trao đổi sinh viên không?",
    "Tín chỉ thực tập có bắt buộc không?",
    "Có được học trực tuyến để lấy tín chỉ không?",
    "Sinh viên có thể tự chọn tín chỉ nghiên cứu không?",
    "Có giới hạn tín chỉ môn học lại không?",
    "Tín chỉ tốt nghiệp bao gồm những gì?",
    "Có thể thay thế tín chỉ tự chọn bằng luận văn không?",
    "Nếu chưa đủ tín chỉ thì có được thi tốt nghiệp không?",
    "Một kỳ hè có thể đăng ký bao nhiêu tín chỉ?",
    "Có thể đăng ký thêm tín chỉ ngoài giờ không?",
    "Có bắt buộc học tín chỉ quốc phòng an ninh không?",
    "Bao lâu thì được công nhận tín chỉ đã học?",
    "Tín chỉ giáo dục thể chất tính vào GPA không?",
    "Có được học vượt tín chỉ trong kỳ cuối không?",
    "Tín chỉ học trực tuyến có giá trị như tín chỉ thường không?",
    "Điểm trung bình được tính như thế nào?",
    "Bao nhiêu điểm thì đạt một môn học?",
    "Điểm F có được học lại không?",
    "Có được phúc khảo điểm thi không?",
    "Điểm phúc khảo có thể tăng giảm không?",
    "Điểm rèn luyện ảnh hưởng thế nào đến học bổng?",
    "Điểm D có tính là đạt không?",
    "Có quy định làm tròn điểm không?",
    "Bao nhiêu điểm thì được loại giỏi?",
    "Bao nhiêu điểm thì bị cảnh báo học vụ?",
    "Có thể hủy kết quả phúc khảo không?",
    "Sinh viên bị điểm F quá nhiều có bị buộc thôi học không?",
    "Khi nào được xem điểm thi?",
    "Có thể thi lại để nâng điểm không?",
    "Điểm quá trình chiếm bao nhiêu phần trăm?",
    "Điểm giữa kỳ có bắt buộc không?",
    "Có được miễn thi nếu đủ điểm quá trình không?",
    "Điểm rèn luyện tối thiểu để được xét học bổng là bao nhiêu?",
    "Có được khiếu nại nếu thấy điểm chấm sai không?",
    "Điểm GPA có được làm tròn không?",
    "Có quy định cộng điểm ưu tiên cho sinh viên chính sách không?",
    "Điểm 4.0 quy đổi ra thang 10 là bao nhiêu?",
    "Điểm học phần có bao gồm điểm chuyên cần không?",
    "Điểm học lại có thay thế điểm cũ không?",
    "Nếu điểm thấp thì có thể học cải thiện không?",
    "Có được xóa điểm môn học không?",
    "Điểm bảo lưu có tính vào GPA không?",
    "Điểm rèn luyện được chấm theo tiêu chí nào?",
    "Bao lâu thì công bố điểm phúc khảo?",
    "Có được xem lại bài thi khi phúc khảo không?",
    "Điểm tốt nghiệp tính bằng điểm trung bình tích lũy đúng không?",
    "Có cộng điểm thưởng cho hoạt động ngoại khóa không?",
    "Điểm chuyên cần chiếm bao nhiêu phần trăm?",
    "Điểm dưới 5 có được học cải thiện không?",
    "Có thể xin thi lại vì lý do cá nhân không?",
    "Điểm thi lại có cao nhất bằng điểm D không?",
    "Có thể nâng điểm bằng cách làm thêm bài tập không?",
    "Điểm kiểm tra miệng có bắt buộc không?",
    "Nếu không có điểm giữa kỳ thì điểm tổng kết tính thế nào?",
    "Có được bảo lưu điểm một số môn không?",
    "Điểm tiếng Anh đầu ra được tính vào GPA không?",
    "Điểm học kỳ có làm tròn lên không?",
    "Có thể xin đặc cách qua môn không?",
    "Điểm dưới 4.0 có phải học lại không?",
    "Có thể xem bảng điểm online không?",
    "Điểm tốt nghiệp có cộng thêm điểm rèn luyện không?",
    "Điểm đồ án tính như môn học bình thường không?",
    "Có thể khiếu nại nếu giảng viên chấm thiếu điểm không?",
    "Điểm phúc khảo cao hơn có bị giảm xuống không?",
    "Có được mang máy tính vào phòng thi không?",
    "Nếu đi trễ thì có được vào phòng thi không?",
    "Có được dùng tài liệu trong phòng thi không?",
    "Sinh viên bị phát hiện gian lận thì xử lý thế nào?",
    "Có được thi lại nếu vắng mặt có lý do chính đáng không?",
    "Có cần giấy báo dự thi khi vào phòng thi không?",
    "Nếu bị mất giấy báo dự thi thì sao?",
    "Có được đổi ca thi không?",
    "Có được thi sớm hơn lịch không?",
    "Nếu bị ốm trong ngày thi thì xử lý thế nào?",
    "Có thể xin hoãn thi không?",
    "Sinh viên bị đình chỉ thi thì bị điểm gì?",
    "Có được mang nước uống vào phòng thi không?",
    "Nếu quên thẻ sinh viên có được thi không?",
    "Có được mang điện thoại tắt nguồn vào phòng thi không?",
    "Thời gian thi một tín chỉ là bao lâu?",
    "Có được ra khỏi phòng thi sớm không?",
    "Nếu làm rơi đề thi thì có được phát lại không?",
    "Có thể mang giấy nháp vào phòng thi không?",
    "Có bắt buộc mặc đồng phục khi thi không?",
    "Có được thi bù khi bị bệnh không?",
    "Sinh viên thi trùng lịch thì xử lý thế nào?",
    "Có được mang từ điển vào phòng thi ngoại ngữ không?",
    "Nếu quên bút thì có được mượn bạn cùng phòng thi không?",
    "Có được mang máy tính lập trình vào phòng thi không?",
    "Nếu mất điện trong lúc thi thì xử lý thế nào?",
    "Có được thi lại nhiều lần một môn không?",
    "Nếu làm bài sai mã đề thì sao?",
    "Có được dùng giấy nháp riêng không?",
    "Nếu bị kỷ luật thi thì có bị ghi vào học bạ không?",
    "Có được đổi chỗ ngồi khi thi không?",
    "Có được gia hạn thời gian thi cho sinh viên khuyết tật không?",
    "Nếu phát hiện đề thi bị sai thì xử lý thế nào?",
    "Có được sử dụng tai nghe khi thi ngoại ngữ không?",
    "Có thể thi trực tuyến không?",
    "Nếu thi trực tuyến bị mất kết nối thì sao?",
    "Có quy định riêng khi thi môn thực hành không?",
    "Nếu không tham gia thi thì điểm là bao nhiêu?",
    "Có được thi bổ sung nếu bỏ lỡ kỳ thi chính không?",
    "Sinh viên bị đình chỉ học có được thi không?",
    "Có được mang đồng hồ điện tử vào phòng thi không?",
    "Có thể nộp bài thi sớm không?",
    "Có được làm bài thi bằng bút chì không?",
    "Nếu vi phạm quy chế thi thì có bị hủy kết quả toàn kỳ không?",
    "Có thể xin thi ghép với lớp khác không?",
    "Nếu quên đem thẻ sinh viên thì cần giấy tờ gì để vào thi?",
    "Có được ghi công thức sẵn vào giấy nháp không?",
    "Nếu vi phạm lần đầu thì có bị đình chỉ học không?",
    "Có bắt buộc ký tên vào danh sách thi không?",
    ],
)



routes = [chitchat, Academic_regulation]

def initializeRouter():
    os.makedirs(os.path.dirname(index_path), exist_ok=True)
    
    index = LocalIndex()
    
    if os.path.exists(index_path):
        with open(index_path, "rb") as f:
            index = pickle.load(f)
        rl = SemanticRouter(encoder=encoder, routes=routes, index=index)
        print("Router initialized with loaded index.")
    else:
        rl = SemanticRouter(encoder=encoder, routes=routes, index=index)
        rl.add(routes)
        with open(index_path, "wb") as f:
            pickle.dump(rl.index, f)
        print(f"Index saved to {index_path}")        
    return rl

def main():
    router = initializeRouter()
    
    query = "Học phí ngành Công nghệ là bao nhiêu?"
    print(f"\nRouting query: '{query}'")
    match = router(query).name
    print(f"Matched route: {match}")

    
if __name__ == "__main__":
    main()